### ISSUE TITLE
New Parser Should Accepet Array for Inputs & Outputs

### ISSUE THREAD

**Issue by Pika1998** [Pika1998/express-autodocs#18]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The new parser should be able to accept inputs like this
```js
 "inputs":{
        "name":"The username by which he/she logs in",
        "password": "A string password"
      },
      "outputs":{
        "userid":"The id of the new user created",
        "error":"Error message if any"
      }
```

**Comment by rahil1304** [comment]
Hey @Pika1998 
I'd like to take up this issue. Could you please assign it to me?

**Comment by Pika1998** [comment]
@rahil1304  sure :smile:

**Comment by Pika1998** [comment]
@rahil1304, after our long discussion on the previous PR, I have tried to implement tests using chai & mocha, I would like you to review #24

**Comment by rahil1304** [comment]
Sure I'll check it out @Pika1998

**Comment by Pika1998** [comment]
@rahil1304  thanks, I tried to add you as a reviewer but it's not suggesting there, but you can review it anyways I guess :smile:

**Comment by rahil1304** [comment]
Hey @Pika1998 
So I was thinking about this issue and wondering, what's the advantage of nested objects? Is there a specific use case where "inputs" and "outputs" are required? 
Is there some specific advantage of writing syntax like 
```
 "inputs":{
        "name":"The username by which he/she logs in",
        "password": "A string password"
      },
      "outputs":{
        "userid":"The id of the new user created",
        "error":"Error message if any"
      }
```
instead of 
```
{
        "name":"The username by which he/she logs in",
        "password": "A string password",
        "userid":"The id of the new user created",
        "error":"Error message if any"
}
```

**Comment by Pika1998** [comment]
In API's the logic is that
**inputs** and **outputs** are mapped in the table

example
**inputs**
"inputs":{
name:'The name of the user',
password:'The password of the user'
}

here every key and value is mapped in tabular format in API,
but if we directly make name, password as variables, we won't be able to figure out which are inputs or outputs

**Comment by rahil1304** [comment]
Okay so could we do something like, 

```
/**
 * Represents a book.
 * @constructor
 * @param {string} [inputs] name- The name of the user.
 * @param {string} [inputs] password- The password of the user.
 * @param {string} [outputs] userid- The id of the new user created.
 * @param {string} [outputs] error- Error message if any.
 */
```
basically, jsdoc syntax doesn't allow nested objects like JSON format right, so we need to think of a work-around. Adding the field in square brackets seems like one option. @Pika1998

**Comment by Pika1998** [comment]
This would also do😃

**Comment by rahil1304** [comment]
Hi @Pika1998 
I have raised a PR to solve this issue. Not sure if it is the correct way to do it, but it works fine and solves the purpose. Do review it when you're free and let me know if there are any issues. https://github.com/Pika1998/express-autodocs/pull/26
