### ISSUE TITLE
Serve output folder after running dev script

### ISSUE THREAD

**Issue by Pika1998** [Pika1998/express-autodocs#21]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be better to serve the output folder in development mode so that the users can easily test the output in localhost http server

We can use `serve` module to achieve this

**Comment by rosborne132** [comment]
@Pika1998 Is this issue still up for grabs?

**Comment by Pika1998** [comment]
@rosborne132  yes it is, would you like to work on it?

**Comment by rosborne132** [comment]
@Pika1998 I would!
