### ISSUE TITLE
Need to setup automated tests

### ISSUE THREAD

**Issue by Pika1998** [Pika1998/express-autodocs#3]
Express-autodocs has a need to improve the development environment for this project, I feel adding unit tests, setting up eslint would help.

**Comment by rahil1304** [comment]
Hey, I would like to work on setting up eslint. What kind of styling are you looking for? @Pika1998

**Comment by Pika1998** [comment]
Hey @rahil1304  ESLint has been already setup, checkout [this PR](https://github.com/Pika1998/express-autodocs/pull/9)4

Let me know if you would like to work on something else :)

**Comment by rahil1304** [comment]
Okay yeah my bad. Are there any pending issues that I could work on? @Pika1998

**Comment by Pika1998** [comment]
@rahil1304 yes, actually people are finding it difficult to pass JSON in the comments to define the API's it would be better to implement a JSDoc Like Parser [Check this issue](https://github.com/Pika1998/express-autodocs/issues/4)

Also I have thought of two future plans
1. Creating a workflow generator website (as a helper for those who are finding it difficult to integrate this action)
[ I am working on a Figma prototype for this which will be shared in the issues soon]
2. Adding more output formats for this action (e.g React documentation etc)

**Comment by rahil1304** [comment]
Okay, will check this issue out. 
I was also wondering since you already have tests set up in your repo, why not integrate Travis CI to automate the testing. So every time somebody submits a PR, the tests will be run to make sure the code is not broken. @Pika1998

**Comment by Pika1998** [comment]
I don't have tests in the sense unit tests, I have added a github action for tests ( I don't know about **Travis CI** ), 

Can you check this [test workflow](https://github.com/Pika1998/express-autodocs/blob/master/.github/workflows/node.js.yml)

I am not running `npm run test` (Because I have not yet written any custom tests using chai or mocha)

**Comment by rahil1304** [comment]
So basically Travis CI is a continuous integration service used to build and test software projects. So we can set up your project using Travis CI, so every time a change is made, it is built automatically to make sure the code is not broken. What I can do is add a travis.yml file that will contain the requirements for this project (similar to what is already done in the node.js.yml file). And then you can just link your repository to travis CI and that's it you're done. Your repository is setup with Travis CI. @Pika1998

**Comment by rahil1304** [comment]
So to give you some more details on Travis, we can add checks for the node version, checks for your other packages, run npm install, and build your project automatically. So basically before merging a PR, these tests will be checked to make sure there is no issue. If any of these tests fail, means the new feature is not working with your project, and it can automatically inform the contributor.

**Comment by Pika1998** [comment]
@rahil1304 I got it, but we can add similar tests using github action, so why travis CI, the workflow file I have can build the project run all the scripts we want like `npm install` `npm run test` etc

So is there any particular reason why we need to install Travis CI explicitly?

**Comment by rahil1304** [comment]
No particular reason. Just thought that in the future, when/if the code base becomes more complex it would be more useful. 
Anyways, no issues. I would love to start off by working on this issue https://github.com/Pika1998/express-autodocs/issues/4, could you assign it to me?

**Comment by Pika1998** [comment]
Sure cool 😁

**Comment by Pika1998** [comment]
> No particular reason. Just thought that in the future, when/if the code base becomes more complex it would be more useful. 
> Anyways, no issues. I would love to start off by working on this issue https://github.com/Pika1998/express-autodocs/issues/4, could you assign it to me? @Pika1998 

Can you just comment on that issue, so that I can assign you 😁
