### ISSUE TITLE
npm run dev breaks on windows 

### ISSUE THREAD

**Issue by KulkarniSuraj** [Pika1998/express-autodocs#5]
**Bug Description**
`npm run dev` command does not work on windows

**To Reproduce**
1. `cd express-autodocs`
2. run `npm install`
3. run `npm run dev`
4. Error message: 'NODE_ENV' is not recognized as an internal or external command

**Expected behavior**
NODE_ENV  is set to development and run index.js

**Screenshots**

**Desktop :**
 - OS: Windows 10

**Additional context**
The error occurs because `NODE_ENV=development node index.js `  syntax is not supported by windows

**Possible Solutions**
1. Using modules like `cross-env` or `dotenv` for managing environment variables
2. handling environment variables in index.js

**Comment by Pika1998** [comment]
Thank you for letting me know this issue, I will get back to you in a few minutes 😁

**Comment by Pika1998** [comment]
@KulkarniSuraj, this issue is now fixed, Thank you 😇

The changes have been added to the latest version @ v0.0.2-beta.1, make sure to pull from master to get the latest changes :)

**Comment by Pika1998** [comment]
Oh wait, It breaks in the production mode 😂

**Comment by Pika1998** [comment]
Fixed it by using `dotenv` module to create **.env** file which sets the environment to `development` when we run the dev script
Checkout the PR #7 for more details.

Thank you 😇 Make sure to pull the changes
