### ISSUE TITLE
Add ESLint, Prettier & Husky

### ISSUE THREAD

**Issue by Pika1998** [Pika1998/express-autodocs#8]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We can add ESLint & Prettier in the project to have a cleaner code.

**Comment by Haqverdi** [comment]
i will add

**Comment by syedmuhammadabid** [comment]
@Pika1998 I have added ESLint and Prettier please merge my PR Thanks :)
https://github.com/Pika1998/express-autodocs/pull/9
